### ISSUE TITLE
Stackprof raises NameError when wrapped in Rails environment conditional

### ISSUE THREAD

**Issue by kreopelle** [tmm1/stackprof#160]
Hello! 

A Rails 5 application I support was recently upgraded to run on RubyGems 3.2.7 and Bundler 2. Prior these changes, the application ran on Bundler 1.17. I'm not sure which RubyGems version it ran on. 

It is running on Stackprof 2.11 within a `:development` block. The version was unchanged during the RubyGems/Bundler upgrade.

Stackprof is configured via rack middleware in the `config/application.rb` file: 

```ruby
# config/application.rb

    if Rails.env.development?
      config.middleware.use(StackProf::Middleware, enabled: true, mode: :wall, interval: 1000, save_every: 5)
    end
```

This is the only reference to Stackprof in the application.

When visiting the staging and production stacks and attempting to log into the Rails console, the following error is raised: 
` uninitialized constant MyApp::Application::StackProf (NameError)`

I haven't seen this before. The error puzzles me, as the middleware should only be configured in the development environment.

Stackprof runs without error in my development environment. Attempting to bring up Rails console does not raise an error in the development environment. 

Are there any restrictions for RubyGems or Bundler versions when using Stackprof? 

Any help would be greatly appreciated!

**Comment by ivoanjo** [comment]
Tiny suggestion: You may want to try the usual `::StackProf::Middleware` (adding the `::` prefix), as Ruby seems to be trying to look up your constant in the wrong namespace.

If you already tried it, please ignore my comment :)

**Comment by kreopelle** [comment]
I haven't tried that yet! I'll give it a shot and let you know how it goes! Bumping the version to 2.17 didn't resolve the error.

**Comment by kreopelle** [comment]
This turned out not to be an issue related to stackprof at all! The other updates around our infrastructure caused the development environment configuration to be executed on our servers. The `Rails.env.development?` the stackprof middleware was set in just happened to be the first piece of code executed. 

Thank you @ivoanjo for your advice and timely response! 😄
