### ISSUE TITLE
Problem with Ruby 2.7.6 and version 0.2.20

### ISSUE THREAD

**Issue by samuelvaneck** [tmm1/stackprof#182]
I've got issue's running the latest version of Stackprof, `0.2.20` on Ruby `2.7.6`. The server crashes after 1-2 page clicks.

```
-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0065 p:---- s:0488 e:000487 CFUNC  :results
c:0064 p:0011 s:0484 e:000483 METHOD /Users/user/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/stackprof-0.2.20/lib/stackprof/middleware.rb:51
c:0063 p:0139 s:0476 e:000474 METHOD /Users/user/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/stackprof-0.2.20/lib/stackprof/middleware.rb:34
c:0062 p:0065 s:0469 e:000468 METHOD /Users/user/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/bundler/gems/rails_api_logger-8b12622b7cc4/lib/rails_api_logger/i
c:0061 p:0017 s:0459 e:000458 BLOCK  /Users/user/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36 [FINISH]
```

If needed I can provide the Diagnostic Reports.

**Comment by ms-ati** [comment]
See also #185

**Comment by eregon** [comment]
FWIW the CI also seems to segfault or fail frequently: https://github.com/tmm1/stackprof/actions

**Comment by eregon** [comment]
I think https://github.com/tmm1/stackprof/pull/180/files#r951294711 is the bug

**Comment by eregon** [comment]
History of the related PRs, since I've been through them a couple times:
https://github.com/tmm1/stackprof/pull/150
https://github.com/tmm1/stackprof/pull/172
https://github.com/tmm1/stackprof/pull/180

**Comment by eregon** [comment]
I think we can close this, https://github.com/tmm1/stackprof/pull/186 should fix it.

**Comment by samuelvaneck** [comment]
The MR should indeed fix the issue. We removed the gem from our repository since we didn't use it. I'll close the issue.
