### ISSUE TITLE
Wrong stack in flamegraph

### ISSUE THREAD

**Issue by onyxblade** [tmm1/stackprof#232]
I'm using `rack-mini-profiler`, and for this action:
```ruby
def demo
  [1,2,3,4,5].each{ sleep 0.5 }
  render json: {}
end
```
The `demo` action would appear twice:
![image](https://github.com/user-attachments/assets/93de6ee6-c026-4186-b383-93fd75f07ad6)

Repository to the demo https://github.com/onyxblade/profiler_demo. The link to generate the flamegraph http://127.0.0.1:3000/?pp=flamegraph&flamegraph_ignore_gc=true.

I'm using the latest versions:
ruby 3.3.5
rails 7.2.1
rack-mini-profiler 3.3.1
stackprof 0.2.26

------

In my investigation, the `flamegraph` generated here https://github.com/MiniProfiler/rack-mini-profiler/blob/5e42a57acab20125f910c0f29d82f19e7220ff31/lib/mini_profiler.rb#L313 is already problematic. The frame `HomeController#demo` appeared twice in one sample in the `raw` output. So I think this is probably a problem of `stackprof`?

**Comment by NickLaMuro** [comment]
@onyxblade This seems like it is working correctly to me.

You get one for the controller action itself (so, as your are entering the method itself), and then one for the code that exists inside the block of the `.each` (which is the `Kernel#sleep`.

You can also see on the top level `HomeController#demo`, it also encompasses some `ActionController` parts, which includes then the `render json: {}` stack trace that you also have.

Obviously, this will take up much less time than the total of the `sleep` calls you have in there, hence their relative size.

**Comment by onyxblade** [comment]
@NickLaMuro Thanks! I think I understand it now. When `each` yields, a new frame would be added to run the block content in `HomeController#demo`. And I noticed this is true for other `Array#each` calls.
