### ISSUE TITLE
ability to ignore some methods/path

### ISSUE THREAD

**Issue by schmurfy** [tmm1/stackprof#37]
I have an application using heavily activerecord (not a rails app) and when trying to profile it I get mitigated results...
The problem is that most of what is shown is, without surprises, in activerecord/activesupport which is not really what I want to know, is there a way to ignore activerecord and instead add the time passed in it to the level above it ?

Here is what I currently get (time passed in the method minus time passed in children):
```
 4% do_something
 5%  User.find(...)
 5%    activerecord
 4%     activerecord
 3%       activerecord
 1%         activerecord
```

And here is what I wish:
```
21% do_something
```

is it currently possible ?

**Comment by inkel** [comment]
Yes, please. That's the only feature I'm missing.

**Comment by itsderek23** [comment]
+1

**Comment by Zapotek** [comment]
+1

Right now I have a multi-MB flamegraph that no browser can handle.
