### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by jmthomas** [tmm1/stackprof#45]
It appears no work has been done to support Windows. Is this gem similar to [memory_profiler](https://github.com/SamSaffron/memory_profiler)?

**Comment by tmm1** [comment]
What is the compilation error?

I don't have any experience with win32, but I imagine setitimer() is not implemented. There might be an alternative we can use.. I would refer to the gperftools implementation to see how they implement support for windows.

**Comment by jchatel** [comment]
On Windows 7 64bits with Ruby 2.2.3:
------------------------------------------------

Installing stackprof 0.2.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby/2.2.3/bin/ruby.exe extconf.rb
checking for rb_postponed_job_register_one()... yes
checking for rb_profile_frames()... yes
checking for rb_tracepoint_new()... yes
checking for RUBY_INTERNAL_EVENT_NEWOBJ... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stackprof-i386-mingw32.def
compiling stackprof.c
In file included from stackprof.c:15:0:
c:\ruby\devkit2.0-32bits\mingw\bin\../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/include/sys/time.h:42:13: error: conflicting types for 'gettimeofday'
In file included from c:/Ruby/2.2.3/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from c:/Ruby/2.2.3/include/ruby-2.2.0/ruby/ruby.h:29,
                 from stackprof.c:9:
c:/Ruby/2.2.3/include/ruby-2.2.0/ruby/win32.h:318:12: note: previous declaration of 'gettimeofday' was here
stackprof.c:58:47: error: unknown type name 'siginfo_t'
stackprof.c: In function 'stackprof_start':
stackprof.c:63:22: error: storage size of 'sa' isn't known
stackprof.c:64:22: error: storage size of 'timer' isn't known
stackprof.c:100:20: error: 'stackprof_signal_handler' undeclared (first use in this function)
stackprof.c:100:20: note: each undeclared identifier is reported only once for each function it appears in
stackprof.c:101:16: error: 'SA_RESTART' undeclared (first use in this function)
stackprof.c:101:29: error: 'SA_SIGINFO' undeclared (first use in this function)
stackprof.c:102:2: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
stackprof.c:103:2: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
stackprof.c:103:31: error: 'SIGALRM' undeclared (first use in this function)
stackprof.c:103:41: error: 'SIGPROF' undeclared (first use in this function)
stackprof.c:108:2: warning: implicit declaration of function 'setitimer' [-Wimplicit-function-declaration]
stackprof.c:108:31: error: 'ITIMER_REAL' undeclared (first use in this function)
stackprof.c:108:45: error: 'ITIMER_PROF' undeclared (first use in this function)
stackprof.c:64:22: warning: unused variable 'timer' [-Wunused-variable]
stackprof.c:63:22: warning: unused variable 'sa' [-Wunused-variable]
stackprof.c: In function 'stackprof_stop':
stackprof.c:129:22: error: storage size of 'sa' isn't known
stackprof.c:130:22: error: storage size of 'timer' isn't known
stackprof.c:140:42: error: 'ITIMER_REAL' undeclared (first use in this function)
stackprof.c:140:56: error: 'ITIMER_PROF' undeclared (first use in this function)
stackprof.c:143:16: error: 'SA_RESTART' undeclared (first use in this function)
stackprof.c:145:42: error: 'SIGALRM' undeclared (first use in this function)
stackprof.c:145:52: error: 'SIGPROF' undeclared (first use in this function)
stackprof.c:130:22: warning: unused variable 'timer' [-Wunused-variable]
stackprof.c:129:22: warning: unused variable 'sa' [-Wunused-variable]
stackprof.c: In function 'stackprof_record_sample':
stackprof.c:405:6: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
stackprof.c: At top level:
stackprof.c:427:35: error: unknown type name 'siginfo_t'
stackprof.c: In function 'stackprof_atfork_prepare':
stackprof.c:477:22: error: storage size of 'timer' isn't known
stackprof.c:481:46: error: 'ITIMER_REAL' undeclared (first use in this function)
stackprof.c:481:60: error: 'ITIMER_PROF' undeclared (first use in this function)
stackprof.c:477:22: warning: unused variable 'timer' [-Wunused-variable]
stackprof.c: In function 'stackprof_atfork_parent':
stackprof.c:489:22: error: storage size of 'timer' isn't known
stackprof.c:495:46: error: 'ITIMER_REAL' undeclared (first use in this function)
stackprof.c:495:60: error: 'ITIMER_PROF' undeclared (first use in this function)
stackprof.c:489:22: warning: unused variable 'timer' [-Wunused-variable]
stackprof.c: In function 'Init_stackprof':
stackprof.c:546:5: warning: statement with no effect [-Wunused-value]
stackprof.c: At top level:
stackprof.c:475:1: warning: 'stackprof_atfork_prepare' defined but not used [-Wunused-function]
stackprof.c:487:1: warning: 'stackprof_atfork_parent' defined but not used [-Wunused-function]
stackprof.c:501:1: warning: 'stackprof_atfork_child' defined but not used [-Wunused-function]
make: *** [stackprof.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby/2.2.3/lib/ruby/gems/2.2.0/gems/stackprof-0.2.8 for inspection.
Results logged to C:/Ruby/2.2.3/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/stackprof-0.2.8/gem_make.out

**Comment by dimanyc** [comment]
any updates on this?

**Comment by tmm1** [comment]
Sorry, there are no plans to add win32 support at this time.

**Comment by jchatel** [comment]
How about putting it in the readme then?

**Comment by itsderek23** [comment]
The README now clarifies OS support: https://github.com/tmm1/stackprof#requirements
