### ISSUE TITLE
Identify CPU intensive code

### ISSUE THREAD

**Issue by Zapotek** [tmm1/stackprof#51]
Is there a way to determine what code is causing high CPU usage?

**Comment by tmm1** [comment]
Yes, the profiler shows you which lines of code and methods are most expensive when you run it in cpu mode.

**Comment by Zapotek** [comment]
If I'm understanding the output correctly, it looks like it lists methods by their cumulative CPU time.
So if a lightweight method uses more CPU time than a heavyweight one just because it gets executed more often, it'll be shown as more expensive.

Which is fair I guess, but I was hoping to be able to spot the heavyweight methods, even if executed much less frequently.

Do I have this wrong?
