### ISSUE TITLE
Update release version to add 'add raw option true' commit

### ISSUE THREAD

**Issue by shunsakai** [tmm1/stackprof#54]
[This commit](https://github.com/tmm1/stackprof/commit/e9835f03be05734945cb9918cc56c383858b9981) which solves the error that option `raw: true` does not work in the release version(v0.2.7) is not merged into current release version.
Please add it to release version so that other people can easily use `--flamegraph` option.

**Comment by splattael** [comment]
@tmm1 

Do you plan to release next version of `stackprof` soonish?

There are a quite number of changes since `0.2.7`: https://github.com/tmm1/stackprof/compare/v0.2.7...master :green_heart:

**Comment by tmm1** [comment]
Done

**Comment by splattael** [comment]
Woow, that was fast. Thank you! :heart: :D
