### ISSUE TITLE
Release request of new version for Ruby 2.3/2.4

### ISSUE THREAD

**Issue by hsbt** [tmm1/stackprof#65]
I got `[BUG] frame2iseq: unreachable` error with stackprof-2.8 and Ruby 2.3.0/2.4.0-dev

It fixed at 
https://github.com/tmm1/stackprof/commit/04330f9355f265313e5afd9cac6c07a6e0016781

Could you release new version contained above commit?

**Comment by tmm1** [comment]
Released 0.2.9

**Comment by hsbt** [comment]
@tmm1 Great thanks!
