### ISSUE TITLE
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32] support

### ISSUE THREAD

**Issue by yuankeyang** [tmm1/stackprof#85]
```shell
gem install stackprof
```
throw erros:

> Building native extensions. This could take a while...
> ERROR:  Error installing stackprof:
>       ERROR: Failed to build gem native extension.
>
>    current directory: H:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/stackprof-0.2.10/e
> xt/stackprof
> H:/Ruby24-x64/bin/ruby.exe -r ./siteconf20171109-10456-1l014ll.rb extconf.rb
> checking for rb_postponed_job_register_one()... yes
> checking for rb_profile_frames()... yes
> checking for rb_tracepoint_new()... yes
> checking for RUBY_INTERNAL_EVENT_NEWOBJ... yes
> creating Makefile
> 
> current directory: H:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/stackprof-0.2.10/ext/s
> tackprof
> make "DESTDIR=" clean
> 
> current directory: H:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/stackprof-0.2.10/ext/s
> tackprof
> make "DESTDIR="
> generating stackprof-x64-mingw32.def
> compiling stackprof.c
> In file included from stackprof.c:15:0:
> H:/msys64/mingw64/x86_64-w64-mingw32/include/sys/time.h:42:13: error: conflictin
> g types for 'gettimeofday'
>  int __cdecl gettimeofday(struct timeval *__restrict__,
>             ^~~~~~~~~~~~
> In file included from H:/Ruby24-x64/include/ruby-2.4.0/ruby/defines.h:243:0,
>                  from H:/Ruby24-x64/include/ruby-2.4.0/ruby/ruby.h:36,
>                  from stackprof.c:9:
> H:/Ruby24-x64/include/ruby-2.4.0/ruby/win32.h:295:12: note: previous declaration
>  of 'gettimeofday' was here
>  extern int gettimeofday(struct timeval *, struct timezone *);
>             ^~~~~~~~~~~~
> stackprof.c:58:47: error: unknown type name 'siginfo_t'; did you mean 'ino_t'?
>  static void stackprof_signal_handler(int sig, siginfo_t* sinfo, void* ucontext)
> ;
>                                                ^~~~~~~~~
>                                                ino_t
> stackprof.c: In function 'stackprof_start':
> stackprof.c:63:22: error: storage size of 'sa' isn't known
>     struct sigaction sa;
>                       ^~
> stackprof.c:64:22: error: storage size of 'timer' isn't known
>      struct itimerval timer;
>                       ^~~~~
> stackprof.c:100:20: error: 'stackprof_signal_handler' undeclared (first use in t
> his function); did you mean 'stackprof_newobj_handler'?
>   sa.sa_sigaction = stackprof_signal_handler;
>                     ^~~~~~~~~~~~~~~~~~~~~~~~
>                     stackprof_newobj_handler
> stackprof.c:100:20: note: each undeclared identifier is reported only once for e
> ach function it appears in
> stackprof.c:101:16: error: 'SA_RESTART' undeclared (first use in this function);
>  did you mean 'SW_RESTORE'?
>   sa.sa_flags = SA_RESTART | SA_SIGINFO;
>                 ^~~~~~~~~~
>                 SW_RESTORE
> stackprof.c:101:29: error: 'SA_SIGINFO' undeclared (first use in this function);
>  did you mean 'PAXISINFO'?
>   sa.sa_flags = SA_RESTART | SA_SIGINFO;
>                              ^~~~~~~~~~
>                              PAXISINFO
> stackprof.c:102:2: warning: implicit declaration of function 'sigemptyset' [-Wim
> plicit-function-declaration]
>   sigemptyset(&sa.sa_mask);
>   ^~~~~~~~~~~
> stackprof.c:103:2: warning: implicit declaration of function 'sigaction' [-Wimpl
> icit-function-declaration]
>   sigaction(mode == sym_wall ? SIGALRM : SIGPROF, &sa, NULL);
>   ^~~~~~~~~
> stackprof.c:103:31: error: 'SIGALRM' undeclared (first use in this function); di
> d you mean 'SIGABRT'?
>   sigaction(mode == sym_wall ? SIGALRM : SIGPROF, &sa, NULL);
>                                ^~~~~~~
>                                SIGABRT
> stackprof.c:103:41: error: 'SIGPROF' undeclared (first use in this function); di
> d you mean 'DLGPROC'?
>   sigaction(mode == sym_wall ? SIGALRM : SIGPROF, &sa, NULL);

**Comment by tmm1** [comment]
stackprof does not work on windows. Sorry.
