### ISSUE TITLE
Include gc samples in raw output

### ISSUE THREAD

**Issue by jlfwong** [tmm1/stackprof#86]
Hi there,

I'm working on tooling to convert stackprof output into something consumable by chrome developer tools to generate nice interactive flamegraphs.

![image](https://user-images.githubusercontent.com/150329/32798176-c7fdcdb4-c928-11e7-9592-ddb1c90a91e2.png)

When I was checking the results, I noticed a significant discrepancy between the total sampling profile time and the total wall time elapsed (I am use the `wall` method of sampling). It seems like this is attributable to 2 things: missed samples and gc samples.

It would be nice to include `gc` samples in the `raw` output so they can have corresponding sections of the flamegraph generated for them. I think this is doable by generating a fake stack frame that corresponds to garbage collection. This would help the generated flame charts align more closely with wall time.

If this is something you'd be interested in, I'm happy to try to submit a PR for this.

On a related note, it would be handy to have the walltime of each sample in order to accommodate for missed samples. At the moment, as far as I can tell, it's not possible to identify where in the raw output a missed sample occurred.

P.S. I know there's already flamegraph support via the `flamegraph` gem, but I find the chrome developer tools version much friendlier, and it includes interactive bottoms-up and call-tree methods of inspecting the profiling results.

**Comment by tmm1** [comment]
Ooh, this is very cool!

A fake stack frame for GC is a good idea. Please do submit a PR.

**Comment by jlfwong** [comment]
Great! I'll look into it.

From a quick skim of the source, it's not clear to me why `rb_postponed_job_register_one` is used rather than just invoking `stackprof_job_handler` directly from `stackprof_signal_handler`.

From reading https://balazs.kutilovi.cz/post/ruby-tracing-part-two-rbtrace/, it sounds like postponed jobs are run when the process receives a signal, but isn't `stackprof_signal_handler` already only called due to a signal being received?

Is it necessary because otherwise the stack will include only the `stackprof_signal_handler` itself?

The only reason I ask is because I'm unsure whether I'd need to use `rb_postponed_job_register_one` to add the sample for the fake GC frame, or if I can do that synchronously within a function call from `stackprof_job_handler`.

**Comment by tmm1** [comment]
The issue that a signal can come in at any time, including for example when the Ruby VM is setting up a method call. It is not safe to get a ruby stack trace while the ruby stack itself is being manipulated and may be inconsistent. Doing so would quickly segfault the process.

Thus we use the postponed_job api to grab a stack trace as soon as the VM is consistent enough to do so.

For the GC case, I think you can just add the frame directly since you're only touching stackprof state and not doing anything with the VM.
