### ISSUE TITLE
Include timestamps for each sample

### ISSUE THREAD

**Issue by jlfwong** [tmm1/stackprof#88]
Because we can't guarantee that samples happened at exactly the specified interval, it can be helpful to record timestamps for when each sample actually did occur.

This would allow us to generate sampling profiles that align correctly with wall-times (which can help diagnose where time is really going).

The Chrome sampling profile file format includes a list of timestamps -- one per sample.

Is this something you'd be interesting in accepting a PR for?

If so, I could use some guidance about what the right approach for collecting the timestamps is.

Based on https://stackoverflow.com/questions/12392278/measure-time-in-linux-time-vs-clock-vs-getrusage-vs-clock-gettime-vs-gettimeof, it seems like the safest, most portable way of getting walltime is `gettimeofday()`, though it sounds like there are better options if we have some `#if DARWIN` code in there. The downside of `gettimeofday()` is that it's not monotonic in cases of e.g. leap seconds. Given the purposes of stackprof, that seems like it should be fine?

I'm also interesting in suggestions for how to store the data. It could be stored as a stream of timestamps, or could be stored as a stream of time elapsed since the previous sample, since the absolute timestamps are roughly meaningless.

It also seems tricky to record when each GC sample was recorded, since we accumulate multiple GC samples to be recorded in a single deferred job execution, and we presumably don't want to allocate memory to store the timestamps of the GC samples.

**Comment by tmm1** [comment]
I would use Ruby's Process.clock_gettime to get a monotonic source of timestamps. Just store them directly as doubles.
